name: test

on:
 
  push:
    branches:
      - '*'

jobs:

  test:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Run application tests
      run: |
        npm install
        npm run test
    
    - name: Build container image and run tests from inside of image
      run: |
        docker build -t typescript_eks_app --target test .
